services:
  backend:
    image: nuclearcode070/chatapp-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '5001:5001'
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - chatapp-network

  frontend:
    image: nuclearcode070/chatapp-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '5173:80'
    networks:
      - chatapp-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - chatapp-network

volumes:
  mongo-data:

networks:
  chatapp-network:   